---
title: "Bees"
author: "Alejandra Torres"
date: '2022-05-23'
output: html_document
---

### Loading information about the samples collected
```{r}
#Bees
setwd("~/Documents/Bees/")
metadata <- read.csv('metadata_pollen.csv',header = T)
head(metadata)
colnames(metadata)
```

### Information about the landscape in each marsh
```{r, message=FALSE}
library(dplyr)
library(tidyverse)
library(kableExtra) # For the table
```
```{r}
#Preparing data
temp <- metadata %>% 
  dplyr::select(MarshCode, LandscapeType, Woodland, OpenNatural) %>%
  unique() %>% remove_rownames %>% 
  column_to_rownames('MarshCode') %>%
  mutate(Woodland = gsub('(.)$', '\\1 %', Woodland), OpenNatural= gsub('(.)$', '\\1 %', OpenNatural)) %>% 
  arrange(LandscapeType)
  
## Create the table
kbl(temp, booktabs = T) %>% 
  kable_styling(full_width = F) %>%
  column_spec(1, width = "2cm") 
```

#Diversity in the samples
```{r}
head(metadata)
temp <- metadata %>% 
  dplyr::select(MarshCode, SampleCode, SpeciesType) %>% 
  drop_na()

temp$SpeciesType <- as.character(temp$SpeciesType) 

temp %>%
group_by(MarshCode) %>%
  summarise(Morphotypes = length(unique(SpeciesType)))

## Create the table
kbl(
    temp %>%
group_by(MarshCode) %>%
  summarise(Morphotypes = length(unique(SpeciesType))),
booktabs = T) %>% 
  kable_styling(full_width = F, position = 'center') %>%
  column_spec(1, width = "2cm") 
```
