name: crancnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=4.3.0
  - aom=3.7.1
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.12.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - cython=3.0.10
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=6.1.1
  - filelock=3.13.4
  - fire=0.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - geos=3.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.7.9
  - graphite2=1.3.13
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - humanfriendly=10.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.6
  - imagecodecs=2023.9.18
  - imageio=2.34.0
  - imath=3.1.11
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - ipywidgets=8.1.2
  - isoduration=20.11.0
  - jasper=4.0.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - json5=0.9.25
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.1
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.1.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.26.0
  - jupyterlab_widgets=3.0.10
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libavif16=1.0.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libhwloc=2.10.0
  - libhwy=1.1.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.1.5.1
  - libjxl=0.10.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libopencv=4.8.0
  - libopenvino=2023.0.2
  - libopenvino-arm-cpu-plugin=2023.0.2
  - libopenvino-auto-batch-plugin=2023.0.2
  - libopenvino-auto-plugin=2023.0.2
  - libopenvino-hetero-plugin=2023.0.2
  - libopenvino-ir-frontend=2023.0.2
  - libopenvino-onnx-frontend=2023.0.2
  - libopenvino-paddle-frontend=2023.0.2
  - libopenvino-pytorch-frontend=2023.0.2
  - libopenvino-tensorflow-frontend=2023.0.2
  - libopenvino-tensorflow-lite-frontend=2023.0.2
  - libopus=1.3.1
  - libpng=1.6.43
  - libprotobuf=4.23.4
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.6
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=18.1.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert=7.16.3
  - nbconvert-core=7.16.3
  - nbconvert-pandoc=7.16.3
  - nbformat=5.10.4
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.3
  - notebook=7.1.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - opencv=4.8.0
  - openexr=3.2.2
  - openh264=2.4.0
  - openjpeg=2.5.2
  - openssl=3.2.1
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=24.0
  - pandas=2.2.2
  - pandoc=3.1.13
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.13
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-opencv=4.8.0
  - pybboxes=0.1.6
  - pycocotools=2.0.6
  - pycparser=2.22
  - pygments=2.17.2
  - pyobjc-core=10.2
  - pyobjc-framework-cocoa=10.2
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pytesseract=0.3.13
  - python=3.11.8
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.2.2
  - pytz=2024.1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=26.0.0
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - rav1e=0.6.6
  - readline=8.2
  - referencing=0.34.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - sahi=0.11.15
  - scikit-image=0.22.0
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - segment-anything=1.0
  - send2trash=1.8.3
  - setuptools=69.5.1
  - shapely=2.0.3
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - svt-av1=1.8.0
  - sympy=1.12
  - tbb=2021.12.0
  - termcolor=2.4.0
  - terminado=0.18.1
  - terminaltables=3.1.10
  - threadpoolctl=3.4.0
  - tifffile=2024.2.12
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - torchvision=0.17.2
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ultralytics=8.1.47
  - uri-template=1.3.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - onnx==1.16.0
      - onnxruntime==1.17.3
      - protobuf==5.26.1
